using System;

namespace StorageService.Exceptions
{
	internal sealed class BattleNotFoundException : Exception
	{
		
	}
}